import type { FailureCategory, RecoveryActionType } from "../domain/types.js";

export const HEURISTIC_SCORER_VERSION = "heuristic-v1";

export const BASE_RECOVERY_PROBABILITIES: Record<FailureCategory, Record<RecoveryActionType, number>> = {
  TEMPORARY_FUNDS: { WAIT_NATIVE_RETRY: 0.60, SEND_NUDGE: 0.72, REQUEST_CARD_UPDATE: 0.15, STOP_AND_ESCALATE: 0.05 },
  PAYMENT_METHOD_INVALID: { WAIT_NATIVE_RETRY: 0.10, SEND_NUDGE: 0.35, REQUEST_CARD_UPDATE: 0.82, STOP_AND_ESCALATE: 0.10 },
  BANK_OR_NETWORK: { WAIT_NATIVE_RETRY: 0.75, SEND_NUDGE: 0.30, REQUEST_CARD_UPDATE: 0.10, STOP_AND_ESCALATE: 0.05 },
  CUSTOMER_AUTH_FAILURE: { WAIT_NATIVE_RETRY: 0.30, SEND_NUDGE: 0.65, REQUEST_CARD_UPDATE: 0.25, STOP_AND_ESCALATE: 0.08 },
  MANDATE_OR_AUTH_INVALID: { WAIT_NATIVE_RETRY: 0.05, SEND_NUDGE: 0.20, REQUEST_CARD_UPDATE: 0.35, STOP_AND_ESCALATE: 0.55 },
  UNKNOWN: { WAIT_NATIVE_RETRY: 0.40, SEND_NUDGE: 0.35, REQUEST_CARD_UPDATE: 0.20, STOP_AND_ESCALATE: 0.15 },
};

export const RECOVERY_SCORE_ADJUSTMENTS = {
  nativeRetryAvailable: 0.10,
  nativeRetryUnavailable: -0.30,
  activeDowntime: { WAIT_NATIVE_RETRY: 0.15, SEND_NUDGE: -0.10, REQUEST_CARD_UPDATE: -0.10 },
  repeatedFailure: { WAIT_NATIVE_RETRY: -0.15, STOP_AND_ESCALATE: 0.15 },
  strongRecoveryHistory: { WAIT_NATIVE_RETRY: 0.05, SEND_NUDGE: 0.05 },
  nudgeLimitReached: -0.25,
  halted: { WAIT_NATIVE_RETRY: -0.30, REQUEST_CARD_UPDATE: 0.10, STOP_AND_ESCALATE: 0.10 },
  lowDiagnosisConfidence: { SEND_NUDGE: -0.05, REQUEST_CARD_UPDATE: -0.05 },
} as const;

export const MIN_RECOVERY_PROBABILITY = 0.01;
export const MAX_RECOVERY_PROBABILITY = 0.99;
