"use client";

import Script from "next/script";
import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import type { RazorpayCheckoutResponse } from "@/types";

interface Session { brand: string; plan: { name: string; amountMinor: number; currency: "INR" }; expiresAt: string; checkout: { key: string; subscription_id: string; subscription_card_change: true; name: string; description: string } }
function money(value: number): string { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value / 100); }

export function CardUpdateFlow({ token }: { token: string }) {
  const [session, setSession] = useState<Session | null>(null); const [scriptReady, setScriptReady] = useState(false); const [busy, setBusy] = useState(false); const [complete, setComplete] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiRequest<Session>(`/api/v1/recovery/card-update/${encodeURIComponent(token)}`).then(setSession).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "This recovery session is unavailable.")); }, [token]);
  async function verify(response: RazorpayCheckoutResponse): Promise<void> { setBusy(true); try { await apiRequest("/api/v1/recovery/card-update/verify", { method: "POST", body: JSON.stringify({ token, ...response }) }); setComplete(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Card update verification failed."); } finally { setBusy(false); } }
  function open(): void { if (!session || !scriptReady || !window.Razorpay) { setError("Razorpay Checkout is still loading. Try again shortly."); return; } setError(null); setBusy(true); const checkout = new window.Razorpay({ ...session.checkout, handler: verify, modal: { ondismiss: () => setBusy(false) } }); checkout.open(); }
  if (complete) return <section className="rounded-xl border border-[var(--line)] bg-white p-7"><p className="text-sm font-semibold text-[var(--accent)]">Payment card update verified</p><h1 className="mt-3 text-3xl font-semibold">Thank you.</h1><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">Your card-change interaction was verified. Payment recovery is confirmed separately from authoritative Razorpay payment events.</p></section>;
  return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" onLoad={() => setScriptReady(true)} onError={() => setError("Razorpay Checkout could not be loaded.")} />{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}{session && <section className="rounded-xl border border-[var(--line)] bg-white p-7"><p className="text-sm font-semibold text-[var(--accent)]">CloudDesk subscription</p><h1 className="mt-3 text-3xl font-semibold">Your payment method needs attention.</h1><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">Update the payment card for your subscription securely through Razorpay Checkout.</p><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[var(--muted)]">Plan</dt><dd className="mt-1 font-semibold">{session.plan.name}</dd></div><div><dt className="text-[var(--muted)]">Amount</dt><dd className="mt-1 font-semibold">{money(session.plan.amountMinor)}</dd></div></dl><button type="button" onClick={open} disabled={busy || !scriptReady} aria-busy={busy} className="mt-7 min-h-11 rounded-xl bg-[var(--accent)] px-5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">{busy ? "Opening secure Checkout…" : "Update Payment Card"}</button><p className="mt-4 text-xs text-[var(--muted)]">Session expires {new Date(session.expiresAt).toLocaleString()}.</p></section>}</>;
}
