import mongoose, { Types } from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import type { RecoveryActionType } from "../src/domain/types.js";
import { AuditEvent } from "../src/models/AuditEvent.js";
import { FailureEvent } from "../src/models/FailureEvent.js";
import { RecoveryCase } from "../src/models/RecoveryCase.js";
import { Subscription } from "../src/models/Subscription.js";
import { getRecoveryMetrics } from "../src/services/metrics/RecoveryMetricsService.js";
import { trackRecoveryOutcome } from "../src/services/recovery/RecoveryOutcomeService.js";
import type { NormalizedRazorpayPayment } from "../src/services/razorpay/RazorpayEventNormalizer.js";

let memoryMongo: MongoMemoryServer;
beforeAll(async () => { memoryMongo = await MongoMemoryServer.create(); await mongoose.connect(memoryMongo.getUri()); }, 120_000);
beforeEach(async () => { await Promise.all([AuditEvent.deleteMany({}), FailureEvent.deleteMany({}), RecoveryCase.deleteMany({}), Subscription.deleteMany({})]); });
afterAll(async () => { await mongoose.disconnect(); await memoryMongo.stop(); });

function payment(id: string, invoiceId: string | null, amountMinor = 69900, createdAt = new Date("2026-08-28T13:00:00Z")): NormalizedRazorpayPayment { return { id, invoiceId, amountMinor, currency: "INR", status: "captured", method: "card", orderId: null, createdAt, error: { code: null, description: null, source: null, step: null, reason: null } }; }
async function fixture(options: { openedAt?: Date; status?: string; invoiceId?: string | null; action?: RecoveryActionType | null; actionMetadata?: Record<string, unknown>; actionAt?: Date; risk?: number; subscriptionId?: string } = {}) {
  const subscription = await Subscription.create({ razorpaySubscriptionId: options.subscriptionId ?? `sub_outcome_${new Types.ObjectId()}`, customer: { name: "Fixture", email: "fixture@example.test" }, plan: { name: "CloudDesk Pro", amountMinor: options.risk ?? 69900, currency: "INR" }, status: "pending", razorpayCreatedAt: new Date("2026-08-20T00:00:00Z") });
  const openedAt = options.openedAt ?? new Date("2026-08-28T12:00:00Z"); const failureIds: Types.ObjectId[] = [];
  if (options.invoiceId) { const failure = await FailureEvent.create({ webhookEventId: new Types.ObjectId(), razorpaySubscriptionId: subscription.razorpaySubscriptionId, razorpayPaymentId: `pay_failed_${new Types.ObjectId()}`, razorpayInvoiceId: options.invoiceId, amountMinor: options.risk ?? 69900, currency: "INR", paymentMethod: "card", normalizedCategory: "UNKNOWN", occurredAt: openedAt }); failureIds.push(failure._id); }
  const actions = options.action ? [{ actionId: `action_${new Types.ObjectId()}`, decisionId: `decision_${new Types.ObjectId()}`, type: options.action, status: "EXECUTED", createdAt: options.actionAt ?? openedAt, executedAt: options.actionAt ?? openedAt, failedAt: null, failureReason: null, executionMode: "internal", metadata: options.actionMetadata ?? {} }] : [];
  const recoveryCase = await RecoveryCase.create({ subscriptionId: subscription._id, razorpaySubscriptionId: subscription.razorpaySubscriptionId, status: options.status ?? (options.action ? "ACTION_EXECUTED" : "DIAGNOSED"), openedAt, closedAt: ["STOPPED", "EXHAUSTED"].includes(options.status ?? "") ? openedAt : null, revenueAtRiskMinor: options.risk ?? 69900, recoveredAmountMinor: 0, failureEventIds: failureIds, actions });
  return { subscription, recoveryCase };
}
async function track(subscriptionId: string, value: NormalizedRazorpayPayment, observedAt = value.createdAt ?? new Date()) { return trackRecoveryOutcome({ razorpaySubscriptionId: subscriptionId, payment: value, sourceEventId: `evt_${value.id}`, observedAt }); }

describe("RecoveryOutcome correlation and revenue", () => {
  it("uses exact invoice correlation, caps revenue, and associates WAIT honestly", async () => {
    const { subscription, recoveryCase } = await fixture({ invoiceId: "inv_exact", action: "WAIT_NATIVE_RETRY", actionAt: new Date("2026-08-28T12:30:00Z") }); const result = await track(subscription.razorpaySubscriptionId, payment("pay_exact", "inv_exact", 90000));
    expect(result).toMatchObject({ matched: true, newlyRecovered: true, matchLevel: "EXACT_INVOICE", outcome: { caseMatchConfidence: "HIGH", recoveredAmountMinor: 69900, remainingRiskMinor: 0, actionAtRecovery: "WAIT_NATIVE_RETRY", actionAssociation: "POST_ACTION_ASSOCIATION", actionAssociationConfidence: "MEDIUM", timeToRecoveryHours: 0.5, recoveredWithin7Days: true } });
    const stored = await RecoveryCase.findById(recoveryCase._id); expect(stored?.status).toBe("RECOVERED"); expect(stored?.actions).toHaveLength(1);
  });
  it("uses a unique recent subscription-only case with medium confidence", async () => { const { subscription } = await fixture(); const result = await track(subscription.razorpaySubscriptionId, payment("pay_fallback", null)); expect(result).toMatchObject({ matchLevel: "SUBSCRIPTION_ONLY", outcome: { caseMatchConfidence: "MEDIUM", actionAssociation: "NO_ACTION_ASSOCIATION" } }); });
  it("does not guess among multiple recent cases", async () => { const first = await fixture(); await RecoveryCase.create({ subscriptionId: first.subscription._id, razorpaySubscriptionId: first.subscription.razorpaySubscriptionId, status: "DETECTED", openedAt: new Date("2026-08-28T12:15:00Z"), revenueAtRiskMinor: 69900, recoveredAmountMinor: 0 }); const result = await track(first.subscription.razorpaySubscriptionId, payment("pay_ambiguous", null)); expect(result.matched).toBe(false); expect(await RecoveryCase.countDocuments({ status: "RECOVERED" })).toBe(0); });
  it("rejects old fallback, success before detection, and unknown subscription", async () => { const old = await fixture({ openedAt: new Date("2026-08-20T00:00:00Z") }); expect((await track(old.subscription.razorpaySubscriptionId, payment("pay_old", null))).matched).toBe(false); const future = await fixture({ openedAt: new Date("2026-08-29T00:00:00Z") }); expect((await track(future.subscription.razorpaySubscriptionId, payment("pay_before", null))).matched).toBe(false); expect((await track("sub_unknown", payment("pay_unknown", null))).matched).toBe(false); });
  it("requires exact invoice evidence for stopped and exhausted cases", async () => { const stopped = await fixture({ status: "STOPPED", invoiceId: "inv_stopped" }); expect((await track(stopped.subscription.razorpaySubscriptionId, payment("pay_stopped_fallback", null))).matched).toBe(false); expect((await track(stopped.subscription.razorpaySubscriptionId, payment("pay_stopped_exact", "inv_stopped"))).matched).toBe(true); const exhausted = await fixture({ status: "EXHAUSTED", invoiceId: "inv_exhausted" }); expect((await track(exhausted.subscription.razorpaySubscriptionId, payment("pay_exhausted", "inv_exhausted"))).matched).toBe(true); });
  it("records partial revenue and remaining risk", async () => { const { subscription } = await fixture({ invoiceId: "inv_partial" }); const result = await track(subscription.razorpaySubscriptionId, payment("pay_partial", "inv_partial", 30000)); expect(result.outcome).toMatchObject({ recoveredAmountMinor: 30000, remainingRiskMinor: 39900 }); });
  it("counts one payment and one outcome only once", async () => { const { subscription, recoveryCase } = await fixture({ invoiceId: "inv_once" }); const first = await track(subscription.razorpaySubscriptionId, payment("pay_once", "inv_once")); const second = await trackRecoveryOutcome({ razorpaySubscriptionId: subscription.razorpaySubscriptionId, payment: payment("pay_once", "inv_once"), sourceEventId: "evt_different", observedAt: new Date("2026-08-28T14:00:00Z") }); expect(first.newlyRecovered).toBe(true); expect(second.newlyRecovered).toBe(false); expect((await RecoveryCase.findById(recoveryCase._id))?.recoveredAmountMinor).toBe(69900); expect(await AuditEvent.countDocuments({ eventType: "REVENUE_RECOVERED" })).toBe(1); });
  it("rejects clearly failed payment evidence", async () => { const { subscription } = await fixture(); const failed = { ...payment("pay_failed_success_event", null), status: "failed" }; expect((await track(subscription.razorpaySubscriptionId, failed)).matched).toBe(false); });
  it.each(["DETECTED", "DIAGNOSED", "DECIDED", "ACTION_PENDING", "ACTION_EXECUTED"])("recovers safely from %s", async (status) => { const { subscription } = await fixture({ status }); const result = await track(subscription.razorpaySubscriptionId, payment(`pay_state_${status}`, null)); expect(result.matched).toBe(true); expect((await RecoveryCase.findOne({ subscriptionId: subscription._id }))?.status).toBe("RECOVERED"); });
});

describe("RecoveryOutcome action association and time", () => {
  it.each([
    ["SEND_NUDGE", { customerContacted: true, deliveryMode: "live" }, "POST_ACTION_ASSOCIATION", "LOW"],
    ["SEND_NUDGE", { customerContacted: false, deliveryMode: "simulation" }, "UNATTRIBUTED", "NONE"],
    ["REQUEST_CARD_UPDATE", { cardUpdateCompleted: true }, "CARD_UPDATE_SEQUENCE", "HIGH"],
    ["STOP_AND_ESCALATE", {}, "UNATTRIBUTED", "NONE"],
  ] as const)("associates %s conservatively", async (action, metadata, association, confidence) => { const { subscription } = await fixture({ invoiceId: `inv_${action}`, action, actionMetadata: metadata }); const result = await track(subscription.razorpaySubscriptionId, payment(`pay_${action}`, `inv_${action}`)); expect(result.outcome).toMatchObject({ actionAtRecovery: action, actionAssociation: association, actionAssociationConfidence: confidence }); });
  it.each([[1, true], [168, true], [169, false]] as const)("calculates %s hour recovery", async (hours, within) => { const openedAt = new Date("2026-08-20T00:00:00Z"); const { subscription } = await fixture({ openedAt, invoiceId: `inv_time_${hours}` }); const result = await track(subscription.razorpaySubscriptionId, payment(`pay_time_${hours}`, `inv_time_${hours}`, 69900, new Date(openedAt.getTime() + hours * 3_600_000))); expect(result.outcome).toMatchObject({ timeToRecoveryHours: hours, recoveredWithin7Days: within }); });
  it("stores null timing for inconsistent timestamps", async () => { const openedAt = new Date("2026-08-28T14:00:00Z"); const { subscription } = await fixture({ openedAt, invoiceId: "inv_negative" }); const result = await track(subscription.razorpaySubscriptionId, payment("pay_negative", "inv_negative", 69900, new Date("2026-08-28T13:00:00Z"))); expect(result.matched).toBe(false); });
});

describe("Recovery metrics", () => {
  it("handles zero cases safely", async () => { expect(await getRecoveryMetrics()).toMatchObject({ totalCases: 0, totalRevenueAtRiskMinor: 0, recoveredCases: 0, observedRecoveredRevenueMinor: 0, unresolvedRevenueMinor: 0, caseRecoveryRate: 0, revenueRecoveryRate: 0, averageTimeToRecoveryHours: null }); });
  it("aggregates observed recovery and action/no-action breakdowns", async () => { const wait = await fixture({ invoiceId: "inv_metrics_wait", action: "WAIT_NATIVE_RETRY" }); await track(wait.subscription.razorpaySubscriptionId, payment("pay_metrics_wait", "inv_metrics_wait")); const noAction = await fixture({ invoiceId: "inv_metrics_none", risk: 30000 }); await track(noAction.subscription.razorpaySubscriptionId, payment("pay_metrics_none", "inv_metrics_none", 15000)); const metrics = await getRecoveryMetrics(); expect(metrics).toMatchObject({ totalCases: 2, totalRevenueAtRiskMinor: 99900, recoveredCases: 2, observedRecoveredRevenueMinor: 84900, unresolvedRevenueMinor: 15000, caseRecoveryRate: 1, recoveredWithin7DaysCount: 2, recoveredWithoutExecutedAction: 1, recoveredRevenueWithoutExecutedActionMinor: 15000, actionBreakdown: { WAIT_NATIVE_RETRY: { casesExecuted: 1, casesRecoveredAfterAction: 1, recoveredRevenueObservedMinor: 69900 } }, associationBreakdown: { POST_ACTION_ASSOCIATION: 1, NO_ACTION_ASSOCIATION: 1 } }); expect(metrics.revenueRecoveryRate).toBeCloseTo(84900 / 99900); });
});
